### ISSUE TITLE
最新版opencv报错 cannot import name '_registerMatType' from 'cv2.cv2

### ISSUE THREAD

**Issue by SlightDust** [ArknightsAutoHelper/ArknightsAutoHelper#312]
```
...............

Collecting opencv-contrib-python>=4.5.4.58
  Downloading http://mirrors.aliyun.com/pypi/packages/14/b9/7ceb503bd497c41665ba39724b2c86dd0224acfa5a300127a049001509bc/opencv_contrib_python-4.5.5.62-cp36-abi3-win32.whl (32.0 MB)
     |████████████████████████████████| 32.0 MB 1.7 MB/s

....................

Successfully installed opencv-contrib-python-4.5.5.62

..................

PS D:\Apps\ArknightsAutoHelper> python39 .\akhelper.py
Traceback (most recent call last):
  File "D:\Apps\ArknightsAutoHelper\akhelper.py", line 9, in <module>
    import Arknights.configure_launcher
  File "D:\Apps\ArknightsAutoHelper\Arknights\configure_launcher.py", line 1, in <module>
    from .helper import ArknightsHelper
  File "D:\Apps\ArknightsAutoHelper\Arknights\helper.py", line 10, in <module>
    from automator import BaseAutomator
  File "D:\Apps\ArknightsAutoHelper\automator\__init__.py", line 3, in <module>
    from .helper import BaseAutomator
  File "D:\Apps\ArknightsAutoHelper\automator\helper.py", line 17, in <module>
    from .connector.ADBConnector import ADBConnector
  File "D:\Apps\ArknightsAutoHelper\automator\connector\ADBConnector.py", line 17, in <module>
    from util import cvimage as Image
  File "D:\Apps\ArknightsAutoHelper\util\cvimage.py", line 15, in <module>
    import cv2
  File "D:\Python\Python39-32\lib\site-packages\cv2\__init__.py", line 9, in <module>
    from .cv2 import _registerMatType
ImportError: cannot import name '_registerMatType' from 'cv2.cv2' (D:\Python\Python39-32\lib\site-packages\cv2\cv2.cp39-win32.pyd)
```

尝试手动更换为4.5.4.58后正常运行。  
或许是不是我用32位python的问题？

**Comment by dantmnf** [comment]
最近从 opencv-python 换成了 opencv-contrib-python，但是：
1. pip 没有冲突包机制会直接覆盖安装；
2. opencv 的 python binding 最近修改了初始化方式。

可以尝试删除所有 opencv 相关包后重新安装。

**Comment by pboymt** [comment]
我遇到过，venv里面直接把虚拟环境删除重新配置就好了。
