### ISSUE TITLE
等待画面静止后报错

### ISSUE THREAD

**Issue by lynnguo666-personal** [ArknightsAutoHelper/ArknightsAutoHelper#331]
使用重复作战时出错
关卡 2-9

 Ξ 等待画面静止
Traceback (most recent call last):
  File "automator/launcher.py", line 172, in command_internal
  File "automator/launcher.py", line 301, in cli_handler
  File "Arknights/addons/stage_navigator.py", line 394, in cli_auto
  File "Arknights/addons/stage_navigator.py", line 343, in main_handler
  File "Arknights/addons/contrib/plan.py", line 99, in run_plan
  File "Arknights/addons/stage_navigator.py", line 332, in navigate_and_combat
  File "Arknights/addons/combat.py", line 117, in combat_on_current_stage
  File "Arknights/addons/combat.py", line 345, in operation_once_statemachine
  File "Arknights/addons/combat.py", line 263, in on_operation
  File "automator/mixin.py", line 102, in wait_for_still_image
RuntimeError: 15 秒内画面未静止，最小误差=152，阈值=16

**Comment by lynnguo666-personal** [comment]
经判断，应该是2-9关卡识别有问题

**Comment by dantmnf** [comment]
结算画面有小概率会产生抖动，干扰静止检测

**Comment by lynnguo666-personal** [comment]
问题在于60s后 程序检测到结算页面 但实际关卡尚未结束
