### ISSUE TITLE
初始py错误

### ISSUE THREAD

**Issue by gypsyzz** [ArknightsAutoHelper/ArknightsAutoHelper#333]
在ubuntu环境下初始下载zip和安装requirements.txt后
python版本为3.8
python3 akhelper.py
Traceback (most recent call last):
  File "akhelper.py", line 9, in <module>
    import Arknights.configure_launcher
  File "/home/z/ArknightsAutoHelper-master/Arknights/configure_launcher.py", line 1, in <module>
    from .helper import ArknightsHelper 
  File "/home/z/ArknightsAutoHelper-master/Arknights/helper.py", line 8, in <module>
    import app
  File "/home/z/ArknightsAutoHelper-master/app/__init__.py", line 15, in <module>
    from . import schema
  File "/home/z/ArknightsAutoHelper-master/app/schema.py", line 1, in <module>
    from .schemadef import *
  File "/home/z/ArknightsAutoHelper-master/app/schemadef.py", line 45, in <module>
    class ListField(Field[list[ElementType]]):
TypeError: 'type' object is not subscriptable

**Comment by gypsyzz** [comment]
同为ubuntu20环境，
在3.9下，初始安装会碰到错误：
ImportError: cannot import name '_imaging' from 'PIL' (/usr/lib/python3/dist-packages/PIL/__init__.py)
解决方法：
pip install -U Pillow
