### ISSUE TITLE
卡在战斗结束，无法退出结算界面进行下一次战斗

### ISSUE THREAD

**Issue by Ainmati** [ArknightsAutoHelper/ArknightsAutoHelper#336]
偶尔能进入第二次战斗，但是还是会在下一次卡住

akhelper> conn
 Ξ trying device ADB: 127.0.0.1:5555 (append)
 Ξ adb connect 127.0.0.1:5555
 Ξ trying device ADB: 127.0.0.1:7555 (append)
 Ξ adb connect 127.0.0.1:7555
akhelper adb:127.0.0.1:7555> q
 Ξ 当前理智 21, 关卡消耗 6
 Ξ 理智充足 开始行动
 Ξ 确认编队
 Ξ 等待 60 s
 Ξ 已进行 60.0 s，判断是否结束
 Ξ 已进行 73.9 s，判断是否结束
 Ξ 战斗结束
 Ξ
Traceback (most recent call last):
  File "Arknights/addons/combat.py", line 355, in on_end_operation
  File "imgreco/end_operation.py", line 267, in recognize
  File "imgreco/end_operation.py", line 436, in recognize_20220414
  File "imgreco/end_operation.py", line 89, in tell_group_20220414
  File "imgreco/end_operation.py", line 160, in tell_group_name_ocr
  File "imgreco/ocr/windows_media_ocr_impl.py", line 64, in recognize
  File "imgreco/ocr/windows_media_ocr_impl.py", line 28, in _dump_ocrresult
  File "rotypes/idldsl.py", line 64, in getter
  File "rotypes/inspectable.py", line 42, in astype
  File "rotypes/idldsl.py", line 126, in <lambda>
ValueError: NULL COM pointer access
 Ξ 离开结算画面
 Ξ 第 1 次作战完成
 Ξ 不在关卡界面
 Ξ 不在关卡界面
 Ξ 当前理智 15, 关卡消耗 6
 Ξ 理智充足 开始行动
 Ξ 确认编队
 Ξ 等待 66 s
 Ξ 已进行 0.0 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 0.2 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 0.4 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 0.6 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 1.0 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 1.2 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 1.6 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 1.7 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 2.1 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 2.3 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 2.7 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 2.8 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 3.6 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 3.8 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 4.0 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 4.1 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 4.3 s，判断是否结束
 Ξ 战斗未结束
 Ξ 已进行 23.2 s，判断是否结束
 Ξ 已进行 39.6 s，判断是否结束
 Ξ 已进行 53.0 s，判断是否结束
 Ξ 已进行 68.9 s，判断是否结束
 Ξ 已进行 82.4 s，判断是否结束
 Ξ 战斗结束

**Comment by dantmnf** [comment]
请提供 log 文件夹下包含出错时间的日志（log 文件和 html 文件）

**Comment by Ainmati** [comment]
尝试过重新安装脚本、用三个月内的.bootstrapper文件替换并没有效果
[log.zip](https://github.com/ArknightsAutoHelper/ArknightsAutoHelper/files/8509890/log.zip)

**Comment by dantmnf** [comment]
看起来有两个问题：

一个是掉落分组改用了 OCR 识别，但是两年前加进去的 Windows OCR 识别率不行；

另一个是掉落识别模型的更新 CDN 最近在国内抽风了。

**Comment by Ainmati** [comment]
谢谢！现在改用tesseract可以正常连续战斗，非常感谢你的帮助！
