### ISSUE TITLE
代理异常时无法正常识别

### ISSUE THREAD

**Issue by Prurite** [ArknightsAutoHelper/ArknightsAutoHelper#342]
1. 未能正常识别代理错误对话框
```
 Ξ 已进行 142.5 s，判断是否结束
 Ξ 未处理的对话框：[yesno] OcrResult['——==~—~__']
Traceback (most recent call last):
  File "automator/launcher.py", line 172, in command_internal
  File "automator/launcher.py", line 301, in cli_handler
  File "Arknights/addons/combat.py", line 415, in cli_quick
  File "Arknights/addons/combat.py", line 118, in combat_on_current_stage
  File "Arknights/addons/combat.py", line 388, in operation_once_statemachine
  File "Arknights/addons/combat.py", line 337, in on_operation
RuntimeError: unhandled dialog
```
2. 因代理异常直接导致任务失败时未能识别
P.S. 这次的 SN-10 是真的恶心

**Comment by Prurite** [comment]
```
2022-05-04 12:58:33,854 ! on_prepare @ combat.py:156 ! DEBUG ! 当前画面关卡：5门-9
2022-05-04 12:58:33,854 ! on_prepare @ combat.py:176 ! INFO ! 当前理智 113, 关卡消耗 71
2022-05-04 12:58:33,854 ! on_prepare @ combat.py:207 ! INFO ! 理智充足 开始行动
2022-05-04 12:58:33,855 ! tap_rect @ mixin.py:54 ! DEBUG ! tap_rect (1067.9976, 623.3328, 1074.0024, 653.9976)
2022-05-04 12:58:33,855 ! touch_tap @ ADBConnector.py:514 ! DEBUG ! 点击坐标:(1072,643)
2022-05-04 12:58:34,869 ! operation_once_statemachine @ combat.py:390 ! DEBUG ! state changed to on_troop
2022-05-04 12:58:35,895 ! check_adb_alive @ ADBConnector.py:103 ! DEBUG ! ADB server version 41
2022-05-04 12:58:35,996 ! on_troop @ combat.py:219 ! INFO ! 确认编队
2022-05-04 12:58:35,996 ! tap_rect @ mixin.py:54 ! DEBUG ! tap_rect (1041.9976, 381.3336, 1164.0016, 628.9992000000001)
2022-05-04 12:58:35,996 ! touch_tap @ ADBConnector.py:514 ! DEBUG ! 点击坐标:(1107,512)
2022-05-04 12:58:37,090 ! operation_once_statemachine @ combat.py:390 ! DEBUG ! state changed to on_operation
2022-05-04 12:58:37,090 ! on_operation @ combat.py:241 ! INFO ! 等待 127 s
2022-05-04 13:00:46,291 ! on_operation @ combat.py:254 ! INFO ! 已进行 129.2 s，判断是否结束
2022-05-04 13:00:46,302 ! check_adb_alive @ ADBConnector.py:103 ! DEBUG ! ADB server version 41
2022-05-04 13:00:46,456 ! match_roi @ common.py:270 ! DEBUG ! RoiMatchingResult(roi_name='combat/topbar', score=0.9788397, threshold=0.8, optimal_score=1, bbox=Rect(x=482.6666666666667, y=10.666666666666668, width=242.66666666666669, height=39.33333333333333), context=None)
2022-05-04 13:00:46,458 ! match_roi @ common.py:270 ! DEBUG ! RoiMatchingResult(roi_name='combat/lun', score=-0.15526919, threshold=0.8, optimal_score=1, bbox=Rect(x=824.6666666666667, y=14.666666666666671, width=64.0, height=14.666666666666664), context=None)
2022-05-04 13:00:59,573 ! on_operation @ combat.py:254 ! INFO ! 已进行 142.5 s，判断是否结束
2022-05-04 13:00:59,584 ! check_adb_alive @ ADBConnector.py:103 ! DEBUG ! ADB server version 41
2022-05-04 13:00:59,698 ! match_roi @ common.py:270 ! DEBUG ! RoiMatchingResult(roi_name='combat/topbar', score=0.29641527, threshold=0.8, optimal_score=1, bbox=Rect(x=482.6666666666667, y=10.666666666666668, width=242.66666666666669, height=39.33333333333333), context=None)
2022-05-04 13:00:59,704 ! match_roi @ common.py:270 ! DEBUG ! RoiMatchingResult(roi_name='combat/topbar_camp', score=-0.054977376, threshold=0.8, optimal_score=1, bbox=Rect(x=394.6666666666667, y=10.66666666666667, width=416.6666666666667, height=40.00000000000003), context=None)
2022-05-04 13:00:59,714 ! match_roi @ common.py:270 ! DEBUG ! RoiMatchingResult(roi_name='combat/failed', score=11614.183, threshold=650, optimal_score=0, bbox=Rect(x=78.00000000000001, y=166.6666666666667, width=376.6666666666667, height=388.0000000000001), context=None)
2022-05-04 13:00:59,725 ! match_roi @ common.py:270 ! DEBUG ! RoiMatchingResult(roi_name='combat/ap_return', score=9011.836, threshold=650, optimal_score=0, bbox=Rect(x=498.66666666666686, y=143.33333333333334, width=282.66666666666697, height=442.0), context=None)
2022-05-04 13:00:59,734 ! match_roi @ common.py:270 ! DEBUG ! RoiMatchingResult(roi_name='end_operation/ep10/rhodes_island', score=38402.53, threshold=325, optimal_score=0, bbox=Rect(x=0.0, y=168.66666666666683, width=54.666666666666664, height=202.6666666666665), context=None)
2022-05-04 13:00:59,836 ! on_operation @ combat.py:336 ! ERROR ! 未处理的对话框：[yesno] OcrResult['——==~—~__']
```

**Comment by Prurite** [comment]
![图片](https://user-images.githubusercontent.com/44775584/166904452-618cff2c-883a-4d2e-b7cd-ad9b1db78069.png)
看起来 OCR 有点问题

**Comment by dantmnf** [comment]
![image](https://user-images.githubusercontent.com/2252500/166932399-8c69f236-13f7-4bfc-8c35-0fe700961444.png)
单独拿出来是可以运行的，看来是 tesseract 内部有状态。

**Comment by dantmnf** [comment]
好像又炸了（半恼
