### ISSUE TITLE
AttributeError: module 'imgreco.ocr.dummy' has no attribute 'Engine'

### ISSUE THREAD

**Issue by hexsix** [ArknightsAutoHelper/ArknightsAutoHelper#344]
总之报个异常，看上去像是 ocr 引擎 fallback 到 dummy 之后出现的

装了任何一个 ocr 就能解决（我装了 tesseract-ocr 之后好了

```bash
$ python akhelper.py q 999
Traceback (most recent call last):
  File "/home/hexsix/Projects/ArknightsAutoHelper/akhelper.py", line 11, in <module>
    sys.exit(automator.launcher.main(sys.argv))
  File "/home/hexsix/Projects/ArknightsAutoHelper/automator/launcher.py", line 321, in main
    return targetcmd(argv[1:])
  File "/home/hexsix/Projects/ArknightsAutoHelper/automator/launcher.py", line 301, in cli_handler
    return getattr(helper.addon(owner), func_name)(argv)
  File "/home/hexsix/Projects/ArknightsAutoHelper/Arknights/addons/combat.py", line 416, in cli_quick
    self.combat_on_current_stage(count)
  File "/home/hexsix/Projects/ArknightsAutoHelper/Arknights/addons/combat.py", line 119, in combat_on_current_stage
    self.operation_once_statemachine(c_id, )
  File "/home/hexsix/Projects/ArknightsAutoHelper/Arknights/addons/combat.py", line 389, in operation_once_statemachine
    smobj.state(smobj)
  File "/home/hexsix/Projects/ArknightsAutoHelper/Arknights/addons/combat.py", line 155, in on_prepare
    recoresult = imgreco.before_operation.recognize(screenshot)
  File "/home/hexsix/Projects/ArknightsAutoHelper/imgreco/before_operation.py", line 95, in recognize
    opidtext = stage_reco(opidimg)
  File "/home/hexsix/Projects/ArknightsAutoHelper/imgreco/before_operation.py", line 64, in stage_reco
    engine = acquire_engine_global_cached('zh-cn')
  File "/home/hexsix/Projects/ArknightsAutoHelper/imgreco/ocr/__init__.py", line 51, in acquire_engine_global_cached
    return impl.Engine(lang, **kwargs)
AttributeError: module 'imgreco.ocr.dummy' has no attribute 'Engine'
```

> 我用了两年没装 ocr 也妹问题，啥情况呀

**Comment by dantmnf** [comment]
部分字母数字的识别从土制 OCR 改成 tesseract 了

**Comment by hexsix** [comment]
原来如此
