### ISSUE TITLE
KeyError: 'recognitionOnly'

### ISSUE THREAD

**Issue by heiheiyoyo** [ArknightsAutoHelper/ArknightsAutoHelper#345]
```
Ξ 载入企鹅数据资源...
Ξ 向企鹅数据汇报掉落
Ξ
Traceback (most recent call last):
File "/home/tom/ArknightsAutoHelper/Arknights/addons/combat.py", line 369, in on_end_operation
reportresult = self.penguin_reporter.report(drops)
File "/home/tom/ArknightsAutoHelper/penguin_stats/reporter.py", line 185, in report
if item.item_id in stage['recognitionOnly']:
KeyError: 'recognitionOnly'
Ξ 未上报掉落截图已保存到 /home/tom/ArknightsAutoHelper/screenshot/未上报掉落-1652441130.png
```
开启了企鹅物流掉落汇报
设置如下
```yaml
combat:
# 企鹅物流数据统计
  penguin_stats:
  # 掉落汇报
  # 将关卡掉落上传到企鹅物流数据 (penguin-stats.io)
    enabled: true

  # 企鹅物流数据统计 API 端点
  # global: 全球站；cn: 中国镜像
    endpoint: global

  # 用户 ID
  # 用户 ID 仅用来标记您的上传身份。在不同设备上使用此 ID 登录，可让掉落数据集中于一个账号下，方便管理上传以及查看个人掉落数据。如果为空，则在下一次上传时创建并存储到配置中。
    uid: 114514

  # 汇报特殊活动物品
  # 汇报掉率随活动进度变化的特殊活动物品
    report_special_item: false
```
企鹅物流api中只有活动图才有recognitionOnly键，刷其他关卡（比如我是刷PR-A-1）时会出错

**Comment by heiheiyoyo** [comment]
刷1-7好像没有出现这个问题，刷PR-A-1时遇到的
