### ISSUE TITLE
异常停在“战斗未结束”状态时内存泄漏

### ISSUE THREAD

**Issue by Prurite** [ArknightsAutoHelper/ArknightsAutoHelper#346]
```
 Ξ 已进行 148.5 s，判断是否结束
 Ξ 代理指挥出现失误
 Ξ 放弃关卡
 Ξ 已进行 165.3 s，判断是否结束
 Ξ 退出关卡
 Ξ 战斗未结束
// 省略……
 Ξ 战斗未结束
 Ξ 战斗未结束
 Ξ 战斗未结束
Traceback (most recent call last):
  File "automator/launcher.py", line 172, in command_internal
  File "automator/launcher.py", line 301, in cli_handler
  File "Arknights/addons/combat.py", line 415, in cli_quick
  File "Arknights/addons/combat.py", line 118, in combat_on_current_stage
  File "Arknights/addons/combat.py", line 388, in operation_once_statemachine
  File "Arknights/addons/combat.py", line 299, in on_operation
  File "imgreco/end_operation.py", line 246, in check_end_operation2
cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\core\src\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 16612808 bytes in function 'cv::OutOfMemoryError'
```

如果战斗未结束状态识别次数过多，会导致内存泄漏

**Comment by dantmnf** [comment]
暂时重现不了，可能需要当时的完整 log 和截图
