### ISSUE TITLE
无法正常识别掉落物

### ISSUE THREAD

**Issue by NullForMikko** [ArknightsAutoHelper/ArknightsAutoHelper#347]
战斗结束

检查物品识别模型更新

Traceback (most recent call last):
  File "D:\ArkNightHelper\.bootstrapper\runtime\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "D:\ArkNightHelper\.bootstrapper\runtime\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "D:\ArkNightHelper\.bootstrapper\runtime\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ArkNightHelper\.bootstrapper\runtime\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "D:\ArkNightHelper\.bootstrapper\runtime\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "D:\ArkNightHelper\.bootstrapper\runtime\lib\site-packages\urllib3\connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "D:\ArkNightHelper\.bootstrapper\runtime\lib\site-packages\urllib3\connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "D:\ArkNightHelper\.bootstrapper\runtime\lib\site-packages\urllib3\connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x0000025E3307DBB0>, 'Connection to cdn.jsdelivr.net timed out. (connect timeout=3)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ArkNightHelper\.bootstrapper\runtime\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "D:\ArkNightHelper\.bootstrapper\runtime\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "D:\ArkNightHelper\.bootstrapper\runtime\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='cdn.jsdelivr.net', port=443): Max retries exceeded with url: /gh/triwinds/arknights-ml@latest/inventory/index_itemid_relation.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000025E3307DBB0>, 'Connection to cdn.jsdelivr.net timed out. (connect timeout=3)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Arknights/addons/combat.py", line 356, in on_end_operation
  File "imgreco/end_operation.py", line 276, in recognize
  File "imgreco/end_operation.py", line 435, in recognize_ep10
  File "imgreco/end_operation.py", line 110, in tell_group_ep10
  File "imgreco/item.py", line 132, in tell_item
  File "imgreco/item.py", line 43, in predict_item_dnn
  File "imgreco/itemdb.py", line 32, in load_net
  File "imgreco/itemdb.py", line 56, in update_index_info
  File "imgreco/itemdb.py", line 89, in update_net
  File "imgreco/itemdb.py", line 69, in retry_get
  File "imgreco/itemdb.py", line 65, in retry_get
  File "D:\ArkNightHelper\.bootstrapper\runtime\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "D:\ArkNightHelper\.bootstrapper\runtime\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\ArkNightHelper\.bootstrapper\runtime\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\ArkNightHelper\.bootstrapper\runtime\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "D:\ArkNightHelper\.bootstrapper\runtime\lib\site-packages\requests\adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='cdn.jsdelivr.net', port=443): Max retries exceeded with url: /gh/triwinds/arknights-ml@latest/inventory/index_itemid_relation.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000025E3307DBB0>, 'Connection to cdn.jsdelivr.net timed out. (connect timeout=3)'))

**Comment by dantmnf** [comment]
> `ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000025E3307DBB0>, 'Connection to cdn.jsdelivr.net timed out. (connect timeout=3)'))`

网络问题，请自行寻找解决方法

**Comment by pboymt** [comment]
> > `ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000025E3307DBB0>, 'Connection to cdn.jsdelivr.net timed out. (connect timeout=3)'))`
> 
> 网络问题，请自行寻找解决方法

jsdelivr已经被墙了
