### ISSUE TITLE
不再支持 MuMu 模拟器

### ISSUE THREAD

**Issue by dantmnf** [ArknightsAutoHelper/ArknightsAutoHelper#353]
## 1. 
MuMu 模拟器的屏幕缓冲区格式不是 RGBA_8888，不符合 [AOSP 自 API 17（Android 4.2）以来的约定](https://developer.android.com/reference/android/view/Display#getPixelFormat())。
```
06-06 20:41:51.586  1821  1831 E ImageReader_JNI: Producer output buffer format: 0x3, ImageReader configured format: 0x1
06-06 20:41:51.586  1821  1831 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: CaptureSessionVirtualDisplay
06-06 20:41:51.586  1821  1831 E AndroidRuntime: java.lang.UnsupportedOperationException: The producer output buffer format 0x3 doesn't match the ImageReader's configured buffer format 0x1.
06-06 20:41:51.586  1821  1831 E AndroidRuntime: 	at android.media.ImageReader.nativeImageSetup(Native Method)
06-06 20:41:51.586  1821  1831 E AndroidRuntime: 	at android.media.ImageReader.acquireNextSurfaceImage(ImageReader.java:327)
06-06 20:41:51.586  1821  1831 E AndroidRuntime: 	at android.media.ImageReader.acquireNextImage(ImageReader.java:375)
06-06 20:41:51.586  1821  1831 E AndroidRuntime: 	at xyz.cirno.aah.agent.CaptureSessionVirtualDisplay$2.onImageAvailable(CaptureSessionVirtualDisplay.java:87)
06-06 20:41:51.586  1821  1831 E AndroidRuntime: 	at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:648)
06-06 20:41:51.586  1821  1831 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-06 20:41:51.586  1821  1831 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
06-06 20:41:51.586  1821  1831 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:61)
```

## 2. 
MuMu 模拟器仍在使用 2016 年 1 月发布的 VirtualBox 5.0.14 作为虚拟化内核（Hypervisor），该版本不支持硬件加速 VMCS shadowing，与其他虚拟机/模拟器 **同时（或先后）** 运行将大幅影响 **两者** 性能。
我们认为网易不会对 VM monitor 部分作出任何改进，同时，我们也认为网易并不会修复其中[已知的安全漏洞](https://www.cvedetails.com/vulnerability-list/vendor_id-93/product_id-20406/Oracle-Vm-Virtualbox.html)<sup>[1]</sup>。
<sub>[1] 这一点也适用于其他基于 VirtualBox 的模拟器</sub>

## 3. 
我们在尝试重现问题 1 时，使用了开启嵌套虚拟化和 GPU partitioning 的 Hyper-V 虚拟机<sup>[2]</sup>运行 MuMu 模拟器。
在我们确认 Windows Hypervisor 没有运行的情况下（删除了 hypervisor 内核，即 `hvax64.exe` 和 `hvix64.exe`），MuMu 模拟器依然提示关闭 Hyper-V：
![image](https://user-images.githubusercontent.com/2252500/172229079-e90a4f3e-0fa1-4266-8c8a-738605e63910.png)
为一探究竟，我们找到了 MuMu 模拟器的日志文件：
```
[2022-06-07 01:54:58] [Information] [Thread-0]: [Checker::init]: version: 1.0.0.0
[2022-06-07 01:54:58] [Information] [Thread-0]: [CheckerManager::run]: run command: hyperv
[2022-06-07 01:54:58] [Information] [Thread-0]: [CheckerManager::run]: exist checker: hyperv
[2022-06-07 01:54:58] [Information] [Thread-0]: [IChecker::check]: run checker: hyperv
[2022-06-07 01:54:58] [Information] [Thread-0]: [IChecker::check]: not ignore cache, get result from cache
[2022-06-07 01:54:58] [Information] [Thread-0]: [CacheManager::get]: get command: hyperv
[2022-06-07 01:54:58] [Information] [Thread-0]: [CacheManager::_isCacheExpired]: for command: hyperv
[2022-06-07 01:54:58] [Information] [Thread-0]: [CacheManager::_getLastCacheBootTime]: for command: hyperv
[2022-06-07 01:54:58] [Information] [Thread-0]: [CacheManager::_getString]: for command: hyperv , key: lastBootTime
[2022-06-07 01:54:58] [Information] [Thread-0]: [CacheManager::_getString]: for command: hyperv , result: 
[2022-06-07 01:54:58] [Information] [Thread-0]: [CacheManager::_getLastCacheBootTime]: get string: 
[2022-06-07 01:54:58] [Information] [Thread-0]: [CacheManager::_isCacheExpired]: lastCacheBootTime: 
[2022-06-07 01:54:58] [Information] [Thread-0]: [CacheManager::_isCacheExpired]: latestBootTime: 2022-6-7-1-46-31
[2022-06-07 01:54:58] [Information] [Thread-0]: [CacheManager::_isCacheExpired]: time is not matched, return true, cache is expired
[2022-06-07 01:54:58] [Information] [Thread-0]: [CacheManager::get]: command is expipred, clear cache: hyperv
[2022-06-07 01:54:58] [Information] [Thread-0]: [CacheManager::_clearCache]: for command: hyperv
[2022-06-07 01:54:58] [Information] [Thread-0]: [CacheManager::_setStringValue]: for command: hyperv , key: lastBootTime , value: 
[2022-06-07 01:54:58] [Information] [Thread-0]: [CacheManager::_setIntValue]: for command: hyperv , key: hyperv , value-1
[2022-06-07 01:54:58] [Information] [Thread-0]: [CacheManager::get]: return CacheResult_Expired: hyperv
[2022-06-07 01:54:58] [Information] [Thread-0]: [IChecker::check]: get result from cache: CacheResult_Expired
[2022-06-07 01:54:58] [Information] [Thread-0]: [HyperVChecker::process]: start check
[2022-06-07 01:54:58] [Information] [Thread-0]: [HyperVChecker::process]: with params: 
[2022-06-07 01:54:58] [Information] [Thread-0]: [HyperVDetector::doDetector]: start check
[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: all item: 

主机名:           DESKTOP-UJH50LQ

OS 名称:          Microsoft Windows 11 企业版

OS 版本:          10.0.22000 暂缺 Build 22000

OS 制造商:        Microsoft Corporation

OS 配置:          独立工作站

OS 构建类型:      Multiprocessor Free

注册的所有人:     user

注册的组织:       

产品 ID:          00329-00000-00003-AA916

初始安装日期:     2022/6/7, 0:48:18

系统启动时间:     2022/6/7, 1:46:31

系统制造商:       Microsoft Corporation

系统型号:         Virtual Machine

系统类型:         x64-based PC

处理器:           安装了 1 个处理器。

                  [01]: AMD64 Family 25 Model 33 Stepping 2 AuthenticAMD ~3400 Mhz

BIOS 版本:        Microsoft Corporation Hyper-V UEFI Release v4.1, 2021/5/5

Windows 目录:     C:\Windows

系统目录:         C:\Windows\system32

启动设备:         \Device\HarddiskVolume1

系统区域设置:     zh-cn;中文(中国)

输入法区域设置:   zh-cn;中文(中国)

时区:             (UTC+08:00) 北京，重庆，香港特别行政区，乌鲁木齐

物理内存总量:     8,191 MB

可用的物理内存:   6,185 MB

虚拟内存: 最大值: 10,111 MB

虚拟内存: 可用:   8,294 MB

虚拟内存: 使用中: 1,817 MB

页面文件位置:     C:\pagefile.sys

域:               WORKGROUP

登录服务器:       \\DESKTOP-UJH50LQ

修补程序:         安装了 3 个修补程序。

                  [01]: KB5013628

                  [02]: KB5013943

                  [03]: KB5012674

网卡:             安装了 1 个 NIC。

                  [01]: Microsoft Hyper-V Network Adapter

                      连接名:      以太网 2

                      启用 DHCP:   是

                      DHCP 服务器: 192.168.126.254

                      IP 地址

                        [01]: 192.168.126.139

                        [02]: fe80::d0c0:de02:9106:da28

Hyper-V 要求:     已检测到虚拟机监控程序。将不显示 Hyper-V 所需的功能。


[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item: 

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item: 主机名:           DESKTOP-UJH50LQ

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item: OS 名称:          Microsoft Windows 11 企业版

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item: OS 版本:          10.0.22000 暂缺 Build 22000

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item: OS 制造商:        Microsoft Corporation

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item: OS 配置:          独立工作站

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item: OS 构建类型:      Multiprocessor Free

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item: 注册的所有人:     user

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item: 注册的组织:       

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item: 产品 ID:          00329-00000-00003-AA916

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item: 初始安装日期:     2022/6/7, 0:48:18

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item: 系统启动时间:     2022/6/7, 1:46:31

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item: 系统制造商:       Microsoft Corporation

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item: 系统型号:         Virtual Machine

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item: 系统类型:         x64-based PC

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item: 处理器:           安装了 1 个处理器。

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item:                   [01]: AMD64 Family 25 Model 33 Stepping 2 AuthenticAMD ~3400 Mhz

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item: BIOS 版本:        Microsoft Corporation Hyper-V UEFI Release v4.1, 2021/5/5

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item find hyper-v
[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: kv size is 2
[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: kv key:         Microsoft Corporation Hyper-V UEFI Release v4.1, 2021/5/5

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item: Windows 目录:     C:\Windows

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item: 系统目录:         C:\Windows\system32

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item: 启动设备:         \Device\HarddiskVolume1

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item: 系统区域设置:     zh-cn;中文(中国)

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item: 输入法区域设置:   zh-cn;中文(中国)

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item: 时区:             (UTC+08:00) 北京，重庆，香港特别行政区，乌鲁木齐

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item: 物理内存总量:     8,191 MB

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item: 可用的物理内存:   6,185 MB

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item: 虚拟内存: 最大值: 10,111 MB

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item: 虚拟内存: 可用:   8,294 MB

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item: 虚拟内存: 使用中: 1,817 MB

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item: 页面文件位置:     C:\pagefile.sys

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item: 域:               WORKGROUP

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item: 登录服务器:       \\DESKTOP-UJH50LQ

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item: 修补程序:         安装了 3 个修补程序。

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item:                   [01]: KB5013628

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item:                   [02]: KB5013943

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item:                   [03]: KB5012674

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item: 网卡:             安装了 1 个 NIC。

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item:                   [01]: Microsoft Hyper-V Network Adapter

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item find hyper-v
[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: kv size is 2
[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: kv key:  Microsoft Hyper-V Network Adapter

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item:                       连接名:      以太网 2

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item:                       启用 DHCP:   是

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item:                       DHCP 服务器: 192.168.126.254

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item:                       IP 地址

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item:                         [01]: 192.168.126.139

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item:                         [02]: fe80::d0c0:de02:9106:da28

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item: Hyper-V 要求:     已检测到虚拟机监控程序。将不显示 Hyper-V 所需的功能。

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: item find hyper-v
[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: kv size is 2
[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: kv key:      已检测到虚拟机监控程序。将不显示 Hyper-V 所需的功能。

[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVDetector::doDetector]: has Hyper-v key, return true
[2022-06-07 01:54:59] [Information] [Thread-0]: [HyperVChecker::process]: not passed
[2022-06-07 01:54:59] [Information] [Thread-0]: [IChecker::check]: check is not passed
[2022-06-07 01:54:59] [Information] [Thread-0]: [CacheManager::set]: set command: hyperv, result: 1
[2022-06-07 01:54:59] [Information] [Thread-0]: [CacheManager::_isCacheExpired]: for command: hyperv
[2022-06-07 01:54:59] [Information] [Thread-0]: [CacheManager::_getLastCacheBootTime]: for command: hyperv
[2022-06-07 01:54:59] [Information] [Thread-0]: [CacheManager::_getString]: for command: hyperv , key: lastBootTime
[2022-06-07 01:54:59] [Information] [Thread-0]: [CacheManager::_getString]: for command: hyperv , result: 
[2022-06-07 01:54:59] [Information] [Thread-0]: [CacheManager::_getLastCacheBootTime]: get string: 
[2022-06-07 01:54:59] [Information] [Thread-0]: [CacheManager::_isCacheExpired]: lastCacheBootTime: 
[2022-06-07 01:54:59] [Information] [Thread-0]: [CacheManager::_isCacheExpired]: latestBootTime: 2022-6-7-1-46-31
[2022-06-07 01:54:59] [Information] [Thread-0]: [CacheManager::_isCacheExpired]: time is not matched, return true, cache is expired
[2022-06-07 01:54:59] [Information] [Thread-0]: [CacheManager::get]: cache is expired: hyperv
[2022-06-07 01:54:59] [Information] [Thread-0]: [CacheManager::get]: update cache boot time: hyperv
[2022-06-07 01:54:59] [Information] [Thread-0]: [CacheManager::_updateLastCacheBootTime]: for command: hyperv
[2022-06-07 01:54:59] [Information] [Thread-0]: [CacheManager::_updateLastCacheBootTime]: set latest bootime: 2022-6-7-1-46-31 , command: hyperv
[2022-06-07 01:54:59] [Information] [Thread-0]: [CacheManager::_setStringValue]: for command: hyperv , key: lastBootTime , value: 2022-6-7-1-46-31
[2022-06-07 01:54:59] [Information] [Thread-0]: [CacheManager::set]: set int value: hyperv
[2022-06-07 01:54:59] [Information] [Thread-0]: [CacheManager::_setIntValue]: for command: hyperv , key: hyperv , value1
[2022-06-07 01:54:59] [Information] [Thread-0]: [CacheManager::_setStringValue]: for command: hyperv , key: extra , value: 
[2022-06-07 01:54:59] [Information] [Thread-0]: [CacheManager::_getString]: for command: hyperv , key: extra
[2022-06-07 01:54:59] [Information] [Thread-0]: [CacheManager::_getString]: for command: hyperv , result: 
```

从日志文件可以看出，只要 `systeminfo` 命令的输出中包含 "hyper-v" 字样，即认为 Hyper-V 正在运行从而阻止模拟器启动。而此时友商模拟器已经正常启动运行。
如此草率的判断方式让我们不禁怀疑 MuMu 模拟器其他部分的代码质量。即使我们有办法绕过这个检测，我们也决定（在当前的人手下）不再对 MuMu 模拟器提供支持。
<sub>当前我们只测试兼容 Hyper-V 的模拟器，即 Bluestacks 和 AVD。</sub>
<sub>[2] Hyper-V 的嵌套虚拟化可以正常运行 KVM 和 VirtualBox，而 GPU partitioning 则可以流畅运行各种 3A 大作</sub>

## 扩展阅读
https://github.com/LmeSzinc/AzurLaneAutoScript/issues/871

**Comment by ninthDevilHAUNSTER** [comment]
令人震惊的代码质量（）

**Comment by NadiaSama** [comment]
akhelper-gui.pyw 快速启动报这个错误
```python
Invocation: {"action":"web:connect","args":["list:0"]}
AttributeError: 'NoneType' object has no attribute 'width'
```
也是这个原因么。

**Comment by pboymt** [comment]
靠，这个不就是判断“无SIM卡”的逻辑么？

**Comment by SekiBetu** [comment]
https://airtest.doc.io.netease.com/IDEdocs/device_connection/3_emulator_connection/
网易自己的airtest框架开发组也遇到了黑屏问题，他们自己的框架有自己的解决方案，称为javacap
