### ISSUE TITLE
onnxruntime 缺失 Apple Silicon M1 二进制 wheel

### ISSUE THREAD

**Issue by tonysyz** [ArknightsAutoHelper/ArknightsAutoHelper#361]
```Traceback (most recent call last):
  File "/Users/adm1n/Desktop/ArknightsAutoHelper/automator/launcher.py", line 174, in command_internal
    errorlevel = cmd(argv)
  File "/Users/adm1n/Desktop/ArknightsAutoHelper/automator/launcher.py", line 303, in cli_handler
    return getattr(helper.addon(owner), func_name)(argv)
  File "/Users/adm1n/Desktop/ArknightsAutoHelper/Arknights/addons/stage_navigator.py", line 394, in cli_auto
    self.main_handler(task_list=tasks)
  File "/Users/adm1n/Desktop/ArknightsAutoHelper/Arknights/addons/stage_navigator.py", line 343, in main_handler
    record.func(self.addon(record.owner), count)
  File "/Users/adm1n/Desktop/ArknightsAutoHelper/Arknights/addons/contrib/plan.py", line 99, in run_plan
    c_id, remain = self.addon(StageNavigator).navigate_and_combat(task['stage'], remain)
  File "/Users/adm1n/Desktop/ArknightsAutoHelper/Arknights/addons/stage_navigator.py", line 328, in navigate_and_combat
    self.goto_stage(c_id)
  File "/Users/adm1n/Desktop/ArknightsAutoHelper/Arknights/addons/stage_navigator.py", line 129, in goto_stage
    handler(stage)
  File "/Users/adm1n/Desktop/ArknightsAutoHelper/Arknights/addons/stage_navigator.py", line 121, in <lambda>
    self.handler_cache[stage] = lambda stage: record.navigate(self.addon(record.owner), stage)
  File "/Users/adm1n/Desktop/ArknightsAutoHelper/Arknights/addons/contrib/start_sp_stage/__init__.py", line 120, in run
    self.enter_activity(activity, query_only)
  File "/Users/adm1n/Desktop/ArknightsAutoHelper/Arknights/addons/contrib/start_sp_stage/__init__.py", line 157, in enter_activity
    act_pos_map = self.get_all_act_pos(crop_flag)
  File "/Users/adm1n/Desktop/ArknightsAutoHelper/Arknights/addons/contrib/start_sp_stage/__init__.py", line 189, in get_all_act_pos
    act_map.update(self.get_act_pos_by_icon(cv_screen, icon, crop))
  File "/Users/adm1n/Desktop/ArknightsAutoHelper/Arknights/addons/contrib/start_sp_stage/__init__.py", line 228, in get_act_pos_by_icon
    name = ocr_and_correct(tag_img, available_activity, log_level=logging.DEBUG)
  File "/Users/adm1n/Desktop/ArknightsAutoHelper/Arknights/addons/contrib/start_sp_stage/__init__.py", line 86, in ocr_and_correct
    ocr_str = ocr_for_single_line(img)
  File "/Users/adm1n/Desktop/ArknightsAutoHelper/Arknights/addons/contrib/start_sp_stage/__init__.py", line 63, in ocr_for_single_line
    res = get_ppocr().ocr_single_line(img)
  File "/Users/adm1n/Desktop/ArknightsAutoHelper/imgreco/ppocr_utils.py", line 18, in get_ppocr
    return TextSystem(box_thresh=0.1)
  File "/Users/adm1n/Desktop/ArknightsAutoHelper/venv/lib/python3.9/site-packages/ppocronnx/predict_system.py", line 65, in __init__
    self.text_detector = TextDetector(box_thresh=box_thresh, unclip_ratio=unclip_ratio,
  File "/Users/adm1n/Desktop/ArknightsAutoHelper/venv/lib/python3.9/site-packages/ppocronnx/det/predict_det.py", line 61, in __init__
    sess = ort.InferenceSession(model_data, so)
  File "/Users/adm1n/Desktop/ArknightsAutoHelper/venv/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 335, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/Users/adm1n/Desktop/ArknightsAutoHelper/venv/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 363, in _create_inference_session
    raise ValueError("This ORT build has {} enabled. ".format(available_providers) +
ValueError: This ORT build has ['CoreMLExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['CoreMLExecutionProvider', 'CPUExecutionProvider'], ...)
```

设备：MacBook Air 2020(Apple Silicon M1)

**Comment by dantmnf** [comment]
请尝试 `pip install git+https://github.com/triwinds/ppocr-onnx.git@main`

**Comment by tonysyz** [comment]
输入命令后出现了这个错误
```shell
xxx@xxx-MacBook-Air ~ % pip3.9 install --upgrade --force-reinstall git+https://github.com/triwinds/ppocr-onnx.git@main
Collecting git+https://github.com/triwinds/ppocr-onnx.git@main
  Cloning https://github.com/triwinds/ppocr-onnx.git (to revision main) to /private/var/folders/88/kbss3xxj2f113r8qypdbp6640000gn/T/pip-req-build-lp9k3q7w
  Running command git clone --filter=blob:none --quiet https://github.com/triwinds/ppocr-onnx.git /private/var/folders/88/kbss3xxj2f113r8qypdbp6640000gn/T/pip-req-build-lp9k3q7w
  Resolved https://github.com/triwinds/ppocr-onnx.git to commit a6aa2ee2e38676209cce0402944fa8c499925576
  Preparing metadata (setup.py) ... done
ERROR: Could not find a version that satisfies the requirement onnxruntime (from ppocr-onnx) (from versions: none)
ERROR: No matching distribution found for onnxruntime
```

**Comment by dantmnf** [comment]
onnxruntime 目前没有 darwin arm64 的二进制包，可能要先用 rosetta 2 跑了

**Comment by dantmnf** [comment]
onnxruntime 发新版了，有 M1 和 3.10 了
