### ISSUE TITLE
不明原因bug

### ISSUE THREAD

**Issue by FSeagle** [ArknightsAutoHelper/ArknightsAutoHelper#364]
以下是bug时的内容
akhelper> q
 Ξ trying device ADB: 127.0.0.1:7555 (append)
 Ξ trying device ADB: 127.0.0.1:5555 (append)
 Ξ adb connect 127.0.0.1:5555
Traceback (most recent call last):
  File "automator/launcher.py", line 172, in command_internal
  File "automator/launcher.py", line 301, in cli_handler
  File "Arknights/addons/combat.py", line 415, in cli_quick
  File "Arknights/addons/combat.py", line 118, in combat_on_current_stage
  File "Arknights/addons/combat.py", line 388, in operation_once_statemachine
  File "Arknights/addons/combat.py", line 153, in on_prepare
  File "automator/addon.py", line 94, in device
  File "automator/helper.py", line 63, in device
  File "automator/helper.py", line 56, in _ensure_device
  File "automator/launcher.py", line 47, in request_device_connector
  File "automator/launcher.py", line 155, in _ensure_device
AttributeError: 'NoneType' object has no attribute 'ensure_alive'
以上bug常出现在电脑长时间开机后。比如早上用akhelper刷方舟还好好的，晚上打开akhelper就会出错。不会是几条命令执行完，下一次执行就出错。都是隔一段时间后打开akh和模拟器打算刷图时发现问题，所以期间也不知道自己做了什么事导致bug。
重启电脑后，akh就正常工作了。

**Comment by dantmnf** [comment]
issue 创建时的代码已经没有 `ensure_alive` 标识符，建议更新后再尝试。
